export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER'
export const DELETE_USER = 'DELETE_USER'

export const GET_WATCHES = 'GET_WATCHES'
export const SEARCH_WATCHES = 'SEARCH_WATCHES'
export const RESET_WATCHES = 'RESET_WATCHES'
export const WATCH_RELATED = 'WATCH_RELATED'
export const RESET_SEARCH_FAILED = 'RESET_SEARCH_FAILED'
export const RESET_TOTAL_COST = 'RESET_TOTAL_COST'
export const CLEAR_WATCHES = 'CLEAR_WATCHES'
export const DELETE_WATCH = 'DELETE_WATCH' 

export const SORT_WATCHES = 'SORT_WATCHES'
export const RESET_SORT = 'RESET_SORT'
export const WATCH_MAKER_SORT = 'Watch Maker'
export const WATCH_NAME_SORT = 'Watch Name'
export const NEWEST_TO_OLDEST_SORT = 'Newest to Oldest'
export const OLDEST_TO_NEWEST_SORT = 'Oldest to Newest'
export const NEWEST_TO_OLDEST_WORN_SORT = 'Newest to Oldest Worn'
export const OLDEST_TO_NEWEST_WORN_SORT = 'Oldest to Newest Worn'
export const COST_LOW_TO_HIGH_SORT = 'Cost Low to High'
export const COST_HIGH_TO_LOW_SORT = 'Cost High to Low'